// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/frappyou/backend/models"
)

type AuthPayload struct {
	Success bool         `json:"success"`
	Token   *string      `json:"token,omitempty"`
	User    *models.User `json:"user,omitempty"`
	Error   *string      `json:"error,omitempty"`
}

type CPFValidation struct {
	Valid         bool    `json:"valid"`
	ColaboradorID *int    `json:"colaboradorId,omitempty"`
	Nome          *string `json:"nome,omitempty"`
	HasSystemUser bool    `json:"hasSystemUser"`
	Message       *string `json:"message,omitempty"`
}

type CategoryScores struct {
	Demandas        float64 `json:"demandas"`
	Controle        float64 `json:"controle"`
	Apoio           float64 `json:"apoio"`
	Relacionamentos float64 `json:"relacionamentos"`
	Papel           float64 `json:"papel"`
	Mudanca         float64 `json:"mudanca"`
}

type Colaborador struct {
	ID               int     `json:"id"`
	Cpf              *string `json:"cpf,omitempty"`
	Nome             *string `json:"nome,omitempty"`
	Codinome         *string `json:"codinome,omitempty"`
	EmailEmpresarial *string `json:"emailEmpresarial,omitempty"`
	EmailPessoal     *string `json:"emailPessoal,omitempty"`
	Telefone1        *string `json:"telefone1,omitempty"`
	Telefone2        *string `json:"telefone2,omitempty"`
	Rg               *string `json:"rg,omitempty"`
	Cnh              *string `json:"cnh,omitempty"`
	Sexo             *string `json:"sexo,omitempty"`
	EstadoCivil      *string `json:"estadoCivil,omitempty"`
	DataNascimento   *string `json:"dataNascimento,omitempty"`
	Cargo            *string `json:"cargo,omitempty"`
	Filial           *string `json:"filial,omitempty"`
	Ativo            *bool   `json:"ativo,omitempty"`
	HasSystemUser    bool    `json:"hasSystemUser"`
	SystemUserID     *string `json:"systemUserId,omitempty"`
}

type ColaboradorConnection struct {
	Nodes      []*Colaborador `json:"nodes"`
	TotalCount int            `json:"totalCount"`
}

type ColaboradorFilterInput struct {
	Search *string `json:"search,omitempty"`
	Filial *string `json:"filial,omitempty"`
}

type CreateCalendarEventInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	Type        string  `json:"type"`
	StartDate   string  `json:"startDate"`
	EndDate     string  `json:"endDate"`
	Color       *string `json:"color,omitempty"`
	AllDay      *bool   `json:"allDay,omitempty"`
}

type CreateUserInput struct {
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	Cpf            string    `json:"cpf"`
	Password       string    `json:"password"`
	Role           *UserRole `json:"role,omitempty"`
	EmailPessoal   *string   `json:"emailPessoal,omitempty"`
	Codinome       *string   `json:"codinome,omitempty"`
	Sexo           *string   `json:"sexo,omitempty"`
	DataNascimento string    `json:"dataNascimento"`
	EstadoCivil    *string   `json:"estadoCivil,omitempty"`
	Rg             *string   `json:"rg,omitempty"`
	Cnh            *string   `json:"cnh,omitempty"`
	Telefone1      *string   `json:"telefone1,omitempty"`
	Telefone2      *string   `json:"telefone2,omitempty"`
	Cargo          *string   `json:"cargo,omitempty"`
	Filial         *string   `json:"filial,omitempty"`
}

type CreateVacationInput struct {
	Type      models.VacationType `json:"type"`
	StartDate string              `json:"startDate"`
	EndDate   string              `json:"endDate"`
	Reason    *string             `json:"reason,omitempty"`
	Notes     *string             `json:"notes,omitempty"`
}

type DashboardStats struct {
	TotalUsers       int `json:"totalUsers"`
	TotalAdmins      int `json:"totalAdmins"`
	TotalDocuments   int `json:"totalDocuments"`
	PendingDocuments int `json:"pendingDocuments"`
	TotalVacations   int `json:"totalVacations"`
	PendingVacations int `json:"pendingVacations"`
}

type DocumentConnection struct {
	Nodes      []*models.Document `json:"nodes"`
	TotalCount int                `json:"totalCount"`
	PageInfo   *PageInfo          `json:"pageInfo"`
}

type DocumentFilterInput struct {
	UserID *string                `json:"userId,omitempty"`
	Status *models.DocumentStatus `json:"status,omitempty"`
	Type   *string                `json:"type,omitempty"`
}

type DocumentStats struct {
	TotalDocuments    int `json:"totalDocuments"`
	PendingDocuments  int `json:"pendingDocuments"`
	ApprovedDocuments int `json:"approvedDocuments"`
	RejectedDocuments int `json:"rejectedDocuments"`
}

type Filial struct {
	Nome string `json:"nome"`
}

type FullProfile struct {
	ID               int     `json:"id"`
	Cpf              *string `json:"cpf,omitempty"`
	Nome             *string `json:"nome,omitempty"`
	Codinome         *string `json:"codinome,omitempty"`
	EmailEmpresarial *string `json:"emailEmpresarial,omitempty"`
	EmailPessoal     *string `json:"emailPessoal,omitempty"`
	Telefone1        *string `json:"telefone1,omitempty"`
	Telefone2        *string `json:"telefone2,omitempty"`
	Rg               *string `json:"rg,omitempty"`
	Cnh              *string `json:"cnh,omitempty"`
	Sexo             *string `json:"sexo,omitempty"`
	EstadoCivil      *string `json:"estadoCivil,omitempty"`
	DataNascimento   *string `json:"dataNascimento,omitempty"`
	Cargo            *string `json:"cargo,omitempty"`
	Filial           *string `json:"filial,omitempty"`
}

type LoginInput struct {
	Cpf        string `json:"cpf"`
	Password   string `json:"password"`
	RememberMe *bool  `json:"rememberMe,omitempty"`
}

type Mutation struct {
}

type Notification struct {
	ID        string    `json:"id"`
	Type      string    `json:"type"`
	Title     string    `json:"title"`
	Message   string    `json:"message"`
	CreatedAt time.Time `json:"createdAt"`
}

type PageInfo struct {
	HasNextPage     bool `json:"hasNextPage"`
	HasPreviousPage bool `json:"hasPreviousPage"`
	CurrentPage     int  `json:"currentPage"`
	TotalPages      int  `json:"totalPages"`
}

type Query struct {
}

type SignupInput struct {
	Name     string  `json:"name"`
	Email    string  `json:"email"`
	Cpf      string  `json:"cpf"`
	Password string  `json:"password"`
	Company  *string `json:"company,omitempty"`
	Answers  string  `json:"answers"`
}

type Subscription struct {
}

type SurveyQuestion struct {
	ID             int    `json:"id"`
	Text           string `json:"text"`
	ScaleType      string `json:"scaleType"`
	ScaleDirection string `json:"scaleDirection"`
	Category       string `json:"category"`
}

type UpdateCalendarEventInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Type        *string `json:"type,omitempty"`
	StartDate   *string `json:"startDate,omitempty"`
	EndDate     *string `json:"endDate,omitempty"`
	Color       *string `json:"color,omitempty"`
	AllDay      *bool   `json:"allDay,omitempty"`
}

type UpdateProfileInput struct {
	Nome             *string `json:"nome,omitempty"`
	Codinome         *string `json:"codinome,omitempty"`
	EmailEmpresarial *string `json:"emailEmpresarial,omitempty"`
	EmailPessoal     *string `json:"emailPessoal,omitempty"`
	Telefone1        *string `json:"telefone1,omitempty"`
	Telefone2        *string `json:"telefone2,omitempty"`
	Rg               *string `json:"rg,omitempty"`
	Cnh              *string `json:"cnh,omitempty"`
	Sexo             *string `json:"sexo,omitempty"`
	EstadoCivil      *string `json:"estadoCivil,omitempty"`
	DataNascimento   *string `json:"dataNascimento,omitempty"`
	Cargo            *string `json:"cargo,omitempty"`
	Filial           *string `json:"filial,omitempty"`
}

type UpdateUserInput struct {
	Name     *string `json:"name,omitempty"`
	Email    *string `json:"email,omitempty"`
	Company  *string `json:"company,omitempty"`
	Position *string `json:"position,omitempty"`
}

type UpdateVacationInput struct {
	Type      *models.VacationType `json:"type,omitempty"`
	StartDate *string              `json:"startDate,omitempty"`
	EndDate   *string              `json:"endDate,omitempty"`
	Reason    *string              `json:"reason,omitempty"`
	Notes     *string              `json:"notes,omitempty"`
}

type UserConnection struct {
	Nodes      []*models.User `json:"nodes"`
	TotalCount int            `json:"totalCount"`
	PageInfo   *PageInfo      `json:"pageInfo"`
}

type VacationApprovalInput struct {
	Status       models.VacationStatus `json:"status"`
	RejectReason *string               `json:"rejectReason,omitempty"`
}

type VacationConnection struct {
	Nodes      []*models.Vacation `json:"nodes"`
	TotalCount int                `json:"totalCount"`
	PageInfo   *PageInfo          `json:"pageInfo"`
}

type VacationFilterInput struct {
	UserID    *string                `json:"userId,omitempty"`
	Type      *models.VacationType   `json:"type,omitempty"`
	Status    *models.VacationStatus `json:"status,omitempty"`
	StartDate *string                `json:"startDate,omitempty"`
	EndDate   *string                `json:"endDate,omitempty"`
}

type UserRole string

const (
	UserRoleUser  UserRole = "user"
	UserRoleAdmin UserRole = "admin"
)

var AllUserRole = []UserRole{
	UserRoleUser,
	UserRoleAdmin,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleUser, UserRoleAdmin:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
